#!/bin/bash
set -e

# Base URLs
TRAVELER_API="http://localhost:8000/api"
OWNER_API="http://localhost:8001/api"
BOOKING_API="http://localhost:8003/api"
AGENT_API="http://localhost:8500"

# Cleanup function
cleanup() {
  echo "🧹 Cleaning up database..."
  kubectl exec -it deployment/mongo-deployment -- mongosh airbnb --eval "db.dropDatabase()" > /dev/null
  rm -f host_cookies.txt traveler_cookies.txt
}

# Run cleanup
cleanup

# --- HOST SETUP ---
echo ">>> 1. Creating Host (Monica)..."
HOST_EMAIL="monica@friends.com"
HOST_PASS="cleaning"
curl -s -X POST "$TRAVELER_API/auth/signup" \
  -H "Content-Type: application/json" \
  -d "{\"name\":\"Monica Geller\",\"email\":\"$HOST_EMAIL\",\"password\":\"$HOST_PASS\"}" > /dev/null

echo ">>> 2. Host Logging in..."
curl -s -c host_cookies.txt -X POST "$TRAVELER_API/auth/login" \
  -H "Content-Type: application/json" \
  -d "{\"email\":\"$HOST_EMAIL\",\"password\":\"$HOST_PASS\"}" > /dev/null

echo ">>> 3. Enabling Host Mode..."
curl -s -b host_cookies.txt -X POST "$OWNER_API/host/enable" > /dev/null

echo ">>> 4. Creating Property..."
PROP_CITY="Paris"
PROP_RES=$(curl -s -b host_cookies.txt -X POST "$OWNER_API/properties" \
  -H "Content-Type: application/json" \
  -d '{
    "title": "Monica Apartment",
    "type": "Apartment",
    "price": 250,
    "city": "'"$PROP_CITY"'",
    "bedrooms": 2,
    "bathrooms": 1,
    "capacity": 3
  }')
PROP_ID=$(echo $PROP_RES | jq -r '.id')
echo "Property created: $PROP_ID in $PROP_CITY"

# --- TRAVELER SETUP ---
echo ">>> 5. Creating Traveler (Chandler)..."
TRAVELER_EMAIL="chandler@friends.com"
TRAVELER_PASS="jokes"
curl -s -X POST "$TRAVELER_API/auth/signup" \
  -H "Content-Type: application/json" \
  -d "{\"name\":\"Chandler Bing\",\"email\":\"$TRAVELER_EMAIL\",\"password\":\"$TRAVELER_PASS\"}" > /dev/null

echo ">>> 6. Traveler Logging in..."
curl -s -c traveler_cookies.txt -X POST "$TRAVELER_API/auth/login" \
  -H "Content-Type: application/json" \
  -d "{\"email\":\"$TRAVELER_EMAIL\",\"password\":\"$TRAVELER_PASS\"}" > /dev/null

# --- BOOKING FLOW ---
echo ">>> 7. Traveler Creating Booking..."
START_DATE=$(date -v+20d +%Y-%m-%d)
END_DATE=$(date -v+23d +%Y-%m-%d)

BOOKING_RES=$(curl -s -b traveler_cookies.txt -X POST "$BOOKING_API/bookings" \
  -H "Content-Type: application/json" \
  -d "{
    \"propertyId\": \"$PROP_ID\",
    \"startDate\": \"$START_DATE\",
    \"endDate\": \"$END_DATE\",
    \"guests\": 2
  }")
BOOKING_ID=$(echo $BOOKING_RES | jq -r '.id')
echo "Booking created: $BOOKING_ID"

echo ">>> 8. Host Accepting Booking..."
sleep 2
ACCEPT_RES=$(curl -s -b host_cookies.txt -X POST "$OWNER_API/bookings/$BOOKING_ID/accept")
if echo "$ACCEPT_RES" | grep -q "Accepted"; then
  echo "✅ Host accepted booking."
else
  echo "❌ Host failed to accept booking."
  exit 1
fi

echo ">>> 9. Verifying 'Accepted' Status for Traveler..."
sleep 2
MY_BOOKINGS=$(curl -s -b traveler_cookies.txt -X GET "$BOOKING_API/bookings")
if echo "$MY_BOOKINGS" | grep -q "Accepted"; then
  echo "✅ Traveler sees Accepted booking."
else
  echo "❌ Traveler does NOT see Accepted booking."
  exit 1
fi

# --- AGENT FLOW ---
echo ">>> 10. Agent Generating Trip Plan for Booking..."
# We simulate the request the frontend would make, using the booking details
PLAN_REQ='{
  "booking": {
    "location": "'"$PROP_CITY"'",
    "startDate": "'"$START_DATE"'",
    "endDate": "'"$END_DATE"'",
    "party": {
      "adults": 2,
      "kids": 0,
      "type": "couple"
    },
    "budgetTier": "moderate"
  },
  "preferences": {
    "interests": ["food", "sightseeing"],
    "dietary": [],
    "mobility": "none",
    "notes": "Generated by verification script"
  },
  "freeText": "Plan a romantic weekend",
  "includeWeather": true
}'

echo "Sending Plan Request for $PROP_CITY ($START_DATE to $END_DATE)..."
PLAN_RES=$(curl -s -X POST "$AGENT_API/plan" \
  -H "Content-Type: application/json" \
  -d "$PLAN_REQ")

if echo "$PLAN_RES" | grep -q "itinerary"; then
  echo "✅ Agent returned a valid plan."
  # Extract a bit of the itinerary to show it's real
  echo "Snippet: $(echo $PLAN_RES | cut -c 1-300)..."
else
  echo "❌ Agent failed to return a plan."
  echo "Response: $PLAN_RES"
  exit 1
fi

echo "🎉 COMPLETE SYSTEM VERIFICATION PASSED!"
